before_script:
  - cd frontend/thrift-harbour

stages:
  - publish
  - deploy

publish-fe:
  image: docker:latest
  stage: publish
  tags:
    - deployment-group-15
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  script:
    - pwd
    - echo $SERVER_IP
    - docker --version
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - docker build -t docker.io/group15/frontend:$CI_COMMIT_SHORT_SHA .
    - docker push docker.io/group15/frontend:$CI_COMMIT_SHORT_SHA
  only:
    - development

deploy-fe:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment-group-15
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u=$DOCKER_HUB_USER -p=$DOCKER_HUB_PWD docker.io"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull docker.io/group15/frontend:$CI_COMMIT_SHORT_SHA"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f thrift-harbour-frontend-app || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3000:3000 -e NODE_ENV=production --name thrift-harbour-frontend-app docker.io/group15/frontend:$CI_COMMIT_SHORT_SHA"
  environment:
    name: production
    url: http://172.17.1.50:3000
  only:
    - development
